url: "https://arindia.github.io"
baseurl: "/beta"
name: Arigato
region: Beta

permalink: pretty

twitter: "https://twitter.com/arigatoin"
facebook: "https://www.facebook.com/arigatoindia/"
snapchat: "#"
instagram: "https://www.instagram.com/arigato.in/"
medium:  "https://medium.com/@arigato"
